      *> C:\Users\Welder\Documents\hbsis\owndrawlviewitem.cls
      $SET ALIGN(8)
       78 maxnumberbytes               value h"0FFFFFFF".
      *>>---------------------------------------------------------------
      *>> The size of an object reference
      *>>---------------------------------------------------------------
       78 objectReferenceSize          value length of self.
      *>----------------------------------------------------------------
      *> Return false this is not a metaclass.
      *>----------------------------------------------------------------
      *>----------------------------------------------------------------
      *> Creates a new list view item with lnkNumColumns columns.
      *>----------------------------------------------------------------
      *> OCWIZARD - start standard class methods
      *> OCWIZARD - end standard class methods
      *>----------------------------------------------------------------
      *> Creates a new list view item with lnkNumColumns columns.
      *>----------------------------------------------------------------
